### ISSUE TITLE
The virtual keyboard doesn't get dismissed

### ISSUE THREAD

**Issue by inchw0rm** [healthcare-it-solutions/picos#34]
I have encountered a strange behaviour on ios
- Open the study nurse screen
- try to create a patient
- the keyboard doesn't get dismissed properly after entering all the necessary information. The keyboard stuck in its position is a problem, because it is hiding navigation buttons, so if you can't dismiss it, you are unable to navigate.

**Comment by inchw0rm** [comment]
Another observation is that it doesn't get closed while filling out the questionnaire.

**Comment by mustiwebp** [comment]
Solved in Release 1.13.0
