### ISSUE TITLE
VisitsScreen back button not working.

### ISSUE THREAD

**Issue by S1rDan** [healthcare-it-solutions/picos#89]
On the first page of VisitsScreen the back button isn't working.

**Comment by Utkarsh4517** [comment]
so i just cloned the project on my local, and inside backend.dart "import 'package:picos/secrets.dart';" is imported but this file does not exist. Can you tell me what to do..

**Comment by S1rDan** [comment]
> so i just cloned the project on my local, and inside backend.dart "import 'package:picos/secrets.dart';" is imported but this file does not exist. Can you tell me what to do..

The secrets.dart is just a file with const values with stored URLs Keys for the backend.
If you want to work on anything we'll have to send you this file and credentials for the test backend.
It's the first time someone outside our organization is interested in this project, so I don't know if it's ok to just send you the required information. But I will discuss that within my organization on monday if you want.

**Comment by Utkarsh4517** [comment]
all right

**Comment by S1rDan** [comment]
> all right

The current development branch should now contain everything you need to get started. The Readme contains credentials you can use. Careful: The password has an "O" and a "0". 
Feel free to ask, if you need something.
